version: '3'
services:
  jenkins:
    image: jenkins-terraform-docker
    build:
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    - "50000:50000"
    container_name: jenkins-terraform-docker
    volumes:
    - jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
